newContentEditor = ""
baseURL = "https://kiki-yan.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "kiki_yan"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = ["hugo-video", "even"]
enableGitInfo = true
hasCJKLanguage = true
paginate = 10

disqusShortname = ""
googleAnalytics = ""
copyright = ""

[author]
  name = "kiki_yan"

[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "CF Problems"
  weight = 20
  identifier = "cf-problems"
  url = "/cf-problems/"

[params]
  version = "4.x"
  since = "2026"
  gitRepo = "https://github.com/kiki-yan/kiki-yan.github.io"
  keywords = ["kiki_yan", "blog", "Codeforces"]
  description = "kiki_yan 的新博客"
  highlightInClient = true
  toc = true
  autoCollapseToc = true
  fancybox = false
  mathjax = false
  postMetaInFooter = false
  linkToMarkDown = false
  customCSS = []
  customJS = []
  uglyURLs = false

  [params.busuanzi]
    enable = false
    siteUV = false
    sitePV = false
    pagePV = false

  [params.social]
    b-github = "https://github.com/kiki-yan"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.youtube]
    privacyEnhanced = true

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.tableOfContents]
  startLevel = 1
  endLevel = 4

[minify]
  disableHTML = true
