newContentEditor = ""
baseURL = "https://kiki-yan.github.io"
languageCode = "en"
defaultContentLanguage = "en"
title = "kiki_yan"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = ["hugo-video", "even"]
enableGitInfo = true

hasCJKLanguage = true
paginate = 10

disqusShortname = ""
googleAnalytics = ""
copyright = ""

[author]
  name = "kiki_yan"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[params]
  since = "2021"
  gitRepo = "https://github.com/kiki-yan/kiki-yan.github.io"
  keywords = ["kiki_yan", "blog"]
  description = "Site under maintenance"
  highlightInClient = true
  toc = true
  autoCollapseToc = true
  fancybox = false
  mathjax = false
  postMetaInFooter = false
  linkToMarkDown = false
  customCSS = []
  customJS = []
  uglyURLs = false

  [params.busuanzi]
    enable = false
    siteUV = false
    sitePV = false
    pagePV = false

  [params.social]
    a-email = "mailto:huzhenweitom@gmail.com"
    b-github = "https://github.com/kiki-yan"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.youtube]
    privacyEnhanced = true

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.tableOfContents]
  startLevel = 1
  endLevel = 4

[minify]
  disableHTML = true
